### ISSUE TITLE
Fix Required Modules

### ISSUE THREAD

**Issue by jasonhaymond** [Exploitacious/Auto-M365-TenantMaster#1]
I had to customize this script and figure out which modules were actually required because the script only connected a couple of them.  I would recommend updating the script to connect all the required modules.

**Comment by Exploitacious** [comment]
Can you let me know which modules were not required or what you had issues with? I think the biggest headache is the fact that you need to use the AzureAD*Preview* module, so that may be why you had issues. I'm thinking for my next iteration, I'll try to verify and automatically install all required modules before the script starts. Stay tuned!
